# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: candidate.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='candidate.proto',
  package='',
  syntax='proto2',
  serialized_options=b'\n\021myrtus.interfacesB\014EFCCandidate',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x63\x61ndidate.proto\"\x9d\x01\n\tCandidate\x12\x13\n\x0binput_nodes\x18\x01 \x02(\x03\x12\x14\n\x0coutput_nodes\x18\x02 \x02(\x03\x12\x14\n\x0chidden_nodes\x18\x03 \x02(\x03\x12\x15\n\rhidden_layers\x18\x04 \x02(\x03\x12\x17\n\x0fnodes_per_layer\x18\x05 \x02(\x03\x12\x0e\n\x06\x62iases\x18\x06 \x03(\x02\x12\x0f\n\x07weights\x18\x07 \x03(\x02\x42!\n\x11myrtus.interfacesB\x0c\x45\x46\x43\x43\x61ndidate'
)




_CANDIDATE = _descriptor.Descriptor(
  name='Candidate',
  full_name='Candidate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='input_nodes', full_name='Candidate.input_nodes', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='output_nodes', full_name='Candidate.output_nodes', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hidden_nodes', full_name='Candidate.hidden_nodes', index=2,
      number=3, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hidden_layers', full_name='Candidate.hidden_layers', index=3,
      number=4, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nodes_per_layer', full_name='Candidate.nodes_per_layer', index=4,
      number=5, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='biases', full_name='Candidate.biases', index=5,
      number=6, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='weights', full_name='Candidate.weights', index=6,
      number=7, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=177,
)

DESCRIPTOR.message_types_by_name['Candidate'] = _CANDIDATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Candidate = _reflection.GeneratedProtocolMessageType('Candidate', (_message.Message,), {
  'DESCRIPTOR' : _CANDIDATE,
  '__module__' : 'candidate_pb2'
  # @@protoc_insertion_point(class_scope:Candidate)
  })
_sym_db.RegisterMessage(Candidate)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
