# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: request.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='request.proto',
  package='',
  syntax='proto2',
  serialized_options=b'\n\021myrtus.interfacesB\nEFCRequest',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rrequest.proto\"\xdc\x01\n\x0c\x41gentProfile\x12\x12\n\ncomm_costs\x18\x01 \x02(\x02\x12\x1b\n\x13\x61gent_available_cpu\x18\x02 \x02(\x03\x12\x1e\n\x16\x61gent_available_memory\x18\x03 \x02(\x03\x12\x1d\n\x15\x61gent_utilization_cpu\x18\x04 \x02(\x03\x12%\n\x04type\x18\x05 \x02(\x0e\x32\x17.AgentProfile.AgentType\x12\n\n\x02id\x18\x06 \x02(\x03\")\n\tAgentType\x12\x08\n\x04\x45\x44GE\x10\x00\x12\x07\n\x03\x46OG\x10\x01\x12\t\n\x05\x43LOUD\x10\x02\"`\n\x07Request\x12\x13\n\x0bpod_cpu_req\x18\x01 \x01(\x03\x12\x13\n\x0bpod_mem_req\x18\x02 \x01(\x03\x12\x1d\n\x06\x61gents\x18\x03 \x03(\x0b\x32\r.AgentProfile\x12\x0c\n\x04last\x18\x04 \x02(\x08\x42\x1f\n\x11myrtus.interfacesB\nEFCRequest'
)



_AGENTPROFILE_AGENTTYPE = _descriptor.EnumDescriptor(
  name='AgentType',
  full_name='AgentProfile.AgentType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='EDGE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FOG', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CLOUD', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=197,
  serialized_end=238,
)
_sym_db.RegisterEnumDescriptor(_AGENTPROFILE_AGENTTYPE)


_AGENTPROFILE = _descriptor.Descriptor(
  name='AgentProfile',
  full_name='AgentProfile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='comm_costs', full_name='AgentProfile.comm_costs', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='agent_available_cpu', full_name='AgentProfile.agent_available_cpu', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='agent_available_memory', full_name='AgentProfile.agent_available_memory', index=2,
      number=3, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='agent_utilization_cpu', full_name='AgentProfile.agent_utilization_cpu', index=3,
      number=4, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='AgentProfile.type', index=4,
      number=5, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='AgentProfile.id', index=5,
      number=6, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _AGENTPROFILE_AGENTTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=238,
)


_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pod_cpu_req', full_name='Request.pod_cpu_req', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pod_mem_req', full_name='Request.pod_mem_req', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='agents', full_name='Request.agents', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='last', full_name='Request.last', index=3,
      number=4, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=240,
  serialized_end=336,
)

_AGENTPROFILE.fields_by_name['type'].enum_type = _AGENTPROFILE_AGENTTYPE
_AGENTPROFILE_AGENTTYPE.containing_type = _AGENTPROFILE
_REQUEST.fields_by_name['agents'].message_type = _AGENTPROFILE
DESCRIPTOR.message_types_by_name['AgentProfile'] = _AGENTPROFILE
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AgentProfile = _reflection.GeneratedProtocolMessageType('AgentProfile', (_message.Message,), {
  'DESCRIPTOR' : _AGENTPROFILE,
  '__module__' : 'request_pb2'
  # @@protoc_insertion_point(class_scope:AgentProfile)
  })
_sym_db.RegisterMessage(AgentProfile)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'request_pb2'
  # @@protoc_insertion_point(class_scope:Request)
  })
_sym_db.RegisterMessage(Request)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
