# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stats.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='stats.proto',
  package='',
  syntax='proto2',
  serialized_options=b'\n\021myrtus.interfacesB\010EFCStats',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bstats.proto\"\xd2\x01\n\x05Stats\x12\x1c\n\x14\x65\x64ge_cpu_utilization\x18\x01 \x02(\x02\x12\x1f\n\x17\x65\x64ge_memory_utilization\x18\x02 \x02(\x02\x12\x1b\n\x13\x66og_cpu_utilization\x18\x03 \x02(\x02\x12\x1e\n\x16\x66og_memory_utilization\x18\x04 \x02(\x02\x12\x16\n\x0e\x66og_dependency\x18\x05 \x02(\x02\x12\x18\n\x10\x63loud_dependency\x18\x06 \x02(\x02\x12\x1b\n\x13\x65xecuted_pods_ratio\x18\x07 \x02(\x02\x42\x1d\n\x11myrtus.interfacesB\x08\x45\x46\x43Stats'
)




_STATS = _descriptor.Descriptor(
  name='Stats',
  full_name='Stats',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='edge_cpu_utilization', full_name='Stats.edge_cpu_utilization', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='edge_memory_utilization', full_name='Stats.edge_memory_utilization', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fog_cpu_utilization', full_name='Stats.fog_cpu_utilization', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fog_memory_utilization', full_name='Stats.fog_memory_utilization', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fog_dependency', full_name='Stats.fog_dependency', index=4,
      number=5, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cloud_dependency', full_name='Stats.cloud_dependency', index=5,
      number=6, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='executed_pods_ratio', full_name='Stats.executed_pods_ratio', index=6,
      number=7, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=226,
)

DESCRIPTOR.message_types_by_name['Stats'] = _STATS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Stats = _reflection.GeneratedProtocolMessageType('Stats', (_message.Message,), {
  'DESCRIPTOR' : _STATS,
  '__module__' : 'stats_pb2'
  # @@protoc_insertion_point(class_scope:Stats)
  })
_sym_db.RegisterMessage(Stats)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
